### ISSUE TITLE
undefined when found opportunity

### ISSUE THREAD

**Issue by hatemua** [yuichiroaoki/poly-flashloan-bot#22]
Do you know what is the issue here?
![image_2022-01-10_210654](https://user-images.githubusercontent.com/25553485/148831864-641f6e7a-0780-4168-aff4-fc102b738121.png)

**Comment by iouae** [comment]
> Do you know what is the issue here? ![image_2022-01-10_210654](https://user-images.githubusercontent.com/25553485/148831864-641f6e7a-0780-4168-aff4-fc102b738121.png)

Traceback?

**Comment by iouae** [comment]
Traceback?

**Comment by iouae** [comment]
Would you please provide traceback or something?

**Comment by royshahar** [comment]
poly-flashloan-bot\node_modules\@ethersproject\logger\lib\index.js:199
        var error = new Error(message);
                    ^

Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.5.1)
    at Logger.makeError (D:\crypto\poly-flashloan-bot\node_modules\@ethersproject\logger\lib\index.js:199:21)
    at Logger.throwError (D:\crypto\poly-flashloan-bot\node_modules\@ethersproject\logger\lib\index.js:208:20)
    at JsonRpcProvider.<anonymous> (D:\crypto\poly-flashloan-bot\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:517:54)
    at step (D:\crypto\poly-flashloan-bot\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:48:23)
    at Object.throw (D:\crypto\poly-flashloan-bot\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:29:53)
    at rejected (D:\crypto\poly-flashloan-bot\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:21:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'

**Comment by royshahar** [comment]
![image](https://user-images.githubusercontent.com/59772227/149141536-01c89e50-3400-4bd9-bb5e-ed756f81487b.png)

**Comment by ezera23** [comment]
It happens to me when I have a bad network or 4G... since I use EC2 I definitely don't have anymore this error and these undefined..... I think this issue can be closed....

**Comment by adedade** [comment]
Want to report the same issue has happened to me

```
┌───┬────────┬─────────┬────────┬─────────┬──────┬──────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────┬──────────────────────────┐
│ # │ From   │  Amount │ To     │  Amount │    ± │    % │ Log                                                                                                                                                                                                          │   Time │                Timestamp │     ├───┼────────┼─────────┼────────┼─────────┼──────┼──────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────┼──────────────────────────┤
│ undefined0 │ undefinedDAI    │ undefined1000.00 │ undefinedETH    │ undefined1010.94 │ undefined10.9 │ undefined 1.1 │ undefined                                                                                                                                                                                                             │ undefined  1.2s │ undefined2022-02-07T01:07:59.472Z │1 │ undefined11.5 │ undefined 1.2 │ undefined                                                                                                                                                                               ┌───┬────────┬─────────┬────────┬─────────┬──────┬──────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────┬──────────────────────────┐
│ # │ From   │  Amount │ To     │  Amount │    ± │    % │ Log                                                                                                                                                                                                          │   Time │                Timestamp │     ├───┼────────┼─────────┼────────┼─────────┼──────┼──────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────┼──────────────────────────┤
│ undefined0 │ undefinedDAI    │ undefined1000.00 │ undefinedETH    │ undefined1010.94 │ undefined10.9 │ undefined 1.1 │ undefined                                                                                                                                                                                                             │ undefined  1.2s │ undefined2022-02-07T01:07:59.472Z │1 │ undefined11.5 │ undefined 1.2 │ undefined
```

**Comment by adedade** [comment]
@yuichiroaoki any idea of the above? seems to be a recurring issue 🙇

**Comment by ifeingewgewmlkm** [comment]
I am getting this issue too. Any idea how to solve?
