### ISSUE TITLE
Crash when fetching prices for 1inch

### ISSUE THREAD

**Issue by adedade** [yuichiroaoki/poly-flashloan-bot#46]
```
/Users/adedade/poly-flashloan-bot/dist/inchPrice.js:30
        amount.toString() +
               ^

TypeError: Cannot read properties of undefined (reading 'toString')
    at get1inchQuoteCallUrl (/Users/adedade/poly-flashloan-bot/dist/inchPrice.js:30:16)
    at /Users/adedade/poly-flashloan-bot/dist/inchPrice.js:53:31
    at Generator.next (<anonymous>)
    at fulfilled (/Users/adedade/poly-flashloan-bot/dist/inchPrice.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by adedade** [comment]
I am on the latest master

**Comment by adedade** [comment]
Should we also enable better stacktraces since they reference compiled js instead of ts sources? e.g. https://www.npmjs.com/package/source-map-support

**Comment by adedade** [comment]
My bad, I did forget to run `yarn build` once pulled the latest changes from master :) will keep an eye out if I encounter any other issue
