### ISSUE TITLE
Undefined when opportunity found, followed by invalid Bignumber error message.

### ISSUE THREAD

**Issue by HankHoneymoon** [yuichiroaoki/poly-flashloan-bot#51]
Getting an "undefined" issue when there is profitable arb opportunity on the flash loan bot. I have changed the loan amount, and added several router addresses for different exchanges, as well as a new token.

`│ 19 │ USDC   │ 11111.00 │ WMATIC │ 11096.64 │    -14.4 │   -0.1 │ Getting quote for USDC → WMATIC…                                                                               │        │ 2022-02-07T03:53:51.878Z │ │ WBTC   │ 11111.00 │ WMATIC │   349.05 │ -10761.9 │  -96.9 │ Getting quote for WBTC → WMATIC…                                                                               │        │ 2022-02-07T03:53:51.92
│ undefined20 │ undefinedUSDC   │ undefined11111.00 │ undefinedWBTC   │ undefined11126.36 │ undefined    15.4 │ undefined   0.1 │ undefined                                                                                                               │ undefined  1.7s │ undefined2022-02-07T03:53:53.600Z │C…                                                                                  │   1.0s │ 2022-02-07T03:53:52.91
│ 21 │ USDC   │ 11111.00 │ CRV    │ 10890.26 │   -220.7 │   -2.0 │ Getting quote for CRV → USDC…                                                                                  │   0.8s │ 2022-02-07T03:53:52.67`

No error thrown for this but, I do get the following error which is mentioned in another issue:

`Error: invalid BigNumber value (argument="value", value=undefined, code=INVALID_ARGUMENT, version=bignumber/5.5.0)`

I will look into this myself, and I thank you for any help you can offer.

**Comment by yuichiroaoki** [comment]
My bad. The problem was because of the poor error handling of axios response. Will fix that.

**Comment by HankHoneymoon** [comment]
I am still getting this type of error. Thanks for any help. 

`│ undefined40 │ undefinedUSDT   │ undefined1000.00 │ undefinedDAI      │ undefined1006.05 │ undefined   6.1 │ undefined   0.6 │ undefined │ undefined  3.0s │ undefined2022-02-28T06:19:46.523Z ││   1.7s │ 2022-02-28T06:19:45.292Z │`


Error code: 


```
/mnt/d/code/arbitrage/yuichiroaoki/poly-flashloan-bot2/node_modules/@ethersproject/logger/lib/index.js:199
        var error = new Error(message);
                    ^

Error: invalid BigNumber value (argument="value", value=undefined, code=INVALID_ARGUMENT, version=bignumber/5.5.0)
    at Logger.makeError (/mnt/d/code/arbitrage/yuichiroaoki/poly-flashloan-bot2/node_modules/@ethersproject/logger/lib/index.js:199:21)
    at Logger.throwError (/mnt/d/code/arbitrage/yuichiroaoki/poly-flashloan-bot2/node_modules/@ethersproject/logger/lib/index.js:208:20)
    at Logger.throwArgumentError (/mnt/d/code/arbitrage/yuichiroaoki/poly-flashloan-bot2/node_modules/@ethersproject/logger/lib/index.js:211:21)
    at Function.BigNumber.from (/mnt/d/code/arbitrage/yuichiroaoki/poly-flashloan-bot2/node_modules/@ethersproject/bignumber/lib/bignumber.js:241:23)
    at NumberCoder.encode (/mnt/d/code/arbitrage/yuichiroaoki/poly-flashloan-bot2/node_modules/@ethersproject/abi/lib/coders/number.js:36:39)
    at /mnt/d/code/arbitrage/yuichiroaoki/poly-flashloan-bot2/node_modules/@ethersproject/abi/lib/coders/array.js:74:19
    at Array.forEach (<anonymous>)
    at pack (/mnt/d/code/arbitrage/yuichiroaoki/poly-flashloan-bot2/node_modules/@ethersproject/abi/lib/coders/array.js:60:12)
    at TupleCoder.encode (/mnt/d/code/arbitrage/yuichiroaoki/poly-flashloan-bot2/node_modules/@ethersproject/abi/lib/coders/tuple.js:71:33)
    at AbiCoder.encode (/mnt/d/code/arbitrage/yuichiroaoki/poly-flashloan-bot2/node_modules/@ethersproject/abi/lib/abi-coder.js:93:15) {
  reason: 'invalid BigNumber value',
  code: 'INVALID_ARGUMENT',
  argument: 'value',
  value: undefined
}
```
