### ISSUE TITLE
reason: 'insufficient funds for intrinsic transaction cost',

### ISSUE THREAD

**Issue by pamarthisai** [yuichiroaoki/poly-flashloan-bot#88]
reason: 'insufficient funds for intrinsic transaction cost',
  code: 'INSUFFICIENT_FUNDS',
  error: Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32000,\"message\":\"insufficient funds for gas * price + value\"},\"id\":82}", error={"code":-32000}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f903f6818982097585efd0c8bc1385efd0c8bc1383e4e1c0946b8bfefa7a74efb3f6dcbdd9663ad947fe3ed10a80b903840cdabeba0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000aae10fa31e73287687ce56ec90f81a800361b89800000000000000000000000000000000000000000000000000000004a817c800000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000027100000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000a5e0829caced8ffdd4de3c43696c57f7d7a678ff00000000000000000000000000000000000000000000000000000000000000020000000000000000000000008f3cf7ad23cd3cadbd9735aff958023239c6a0630000000000000000000000000d500b1d8e8ef31e21c99d1db9a6444d3adf12700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000040000000000000000000000000e592427a0aece92de3edee1f18e0157c0586156400000000000000000000000000000000000000000000000000000000000001f400000000000000000000000000000000000000000000000000000000000000020000000000000000000000000d500b1d8e8ef31e21c99d1db9a6444d3adf12700000000000000000000000008f3cf7ad23cd3cadbd9735aff958023239c6a063c001a0f27c77492b08862cf150d60f4236016c7708dc15b18047bc08187d275c3e9193a05a0196fc0c30c1af25d798f10035205a89a7650b8354f60be649a7e140ef88dc\"],\"id\":82,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://polygon-mainnet.g.alchemy.com/v2/hFvhRyorjO0YWqzc-uQW8suTXGQuhA1p", code=SERVER_ERROR, version=web/5.5.1)
      at Logger.makeError (C:\Users\vkart\Desktop\bot\poly-flashloan-bot-main\node_modules\@ethersproject\logger\lib\index.js:199:21)
      at Logger.throwError (C:\Users\vkart\Desktop\bot\poly-flashloan-bot-main\node_modules\@ethersproject\logger\lib\index.js:208:20)
      at C:\Users\vkart\Desktop\bot\poly-flashloan-bot-main\node_modules\@ethersproject\web\lib\index.js:301:32
      at step (C:\Users\vkart\Desktop\bot\poly-flashloan-bot-main\node_modules\@ethersproject\web\lib\index.js:33:23)
      at Object.next (C:\Users\vkart\Desktop\bot\poly-flashloan-bot-main\node_modules\@ethersproject\web\lib\index.js:14:53)
      at fulfilled (C:\Users\vkart\Desktop\bot\poly-flashloan-bot-main\node_modules\@ethersproject\web\lib\index.js:5:58)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    reason: 'processing response error',
    code: 'SERVER_ERROR',
    body: '{"jsonrpc":"2.0","error":{"code":-32000,"message":"insufficient funds for gas * price + value"},"id":82}',
    error: Error: insufficient funds for gas * price + value
        at getResult (C:\Users\vkart\Desktop\bot\poly-flashloan-bot-main\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:142:21)
        at processJsonFunc (C:\Users\vkart\Desktop\bot\poly-flashloan-bot-main\node_modules\@ethersproject\web\lib\index.js:344:22)
        at C:\Users\vkart\Desktop\bot\poly-flashloan-bot-main\node_modules\@ethersproject\web\lib\index.js:276:46
        at step (C:\Users\vkart\Desktop\bot\poly-flashloan-bot-main\node_modules\@ethersproject\web\lib\index.js:33:23)
        at Object.next (C:\Users\vkart\Desktop\bot\poly-flashloan-bot-main\node_modules\@ethersproject\web\lib\index.js:14:53)
        at fulfilled (C:\Users\vkart\Desktop\bot\poly-flashloan-bot-main\node_modules\@ethersproject\web\lib\index.js:5:58)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
      code: -32000,
      data: undefined
    },
    requestBody: '{"method":"eth_sendRawTransaction","params":["0x02f903f6818982097585efd0c8bc1385efd0c8bc1383e4e1c0946b8bfefa7a74efb3f6dcbdd9663ad947fe3ed10a80b903840cdabeba0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000aae10fa31e73287687ce56ec90f81a800361b89800000000000000000000000000000000000000000000000000000004a817c800000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000027100000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000a5e0829caced8ffdd4de3c43696c57f7d7a678ff00000000000000000000000000000000000000000000000000000000000000020000000000000000000000008f3cf7ad23cd3cadbd9735aff958023239c6a0630000000000000000000000000d500b1d8e8ef31e21c99d1db9a6444d3adf12700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000040000000000000000000000000e592427a0aece92de3edee1f18e0157c0586156400000000000000000000000000000000000000000000000000000000000001f400000000000000000000000000000000000000000000000000000000000000020000000000000000000000000d500b1d8e8ef31e21c99d1db9a6444d3adf12700000000000000000000000008f3cf7ad23cd3cadbd9735aff958023239c6a063c001a0f27c77492b08862cf150d60f4236016c7708dc15b18047bc08187d275c3e9193a05a0196fc0c30c1af25d798f10035205a89a7650b8354f60be649a7e140ef88dc"],"id":82,"jsonrpc":"2.0"}',
    requestMethod: 'POST',
    url: 'https://polygon-mainnet.g.alchemy.com/v2/hFvhRyorjO0YWqzc-uQW8suTXGQuhA1p'
  },
  method: 'sendTransaction',
  transaction: {
    type: 2,
    chainId: 137,
    nonce: 2421,
    maxPriorityFeePerGas: BigNumber { _hex: '0xefd0c8bc13', _isBigNumber: true },
    maxFeePerGas: BigNumber { _hex: '0xefd0c8bc13', _isBigNumber: true },
    gasPrice: null,
    gasLimit: BigNumber { _hex: '0xe4e1c0', _isBigNumber: true },
    to: '0x6B8bfEFA7A74eFb3F6dcbdD9663Ad947Fe3ED10A',
    value: BigNumber { _hex: '0x00', _isBigNumber: true },
    data: '0x0cdabeba0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000aae10fa31e73287687ce56ec90f81a800361b89800000000000000000000000000000000000000000000000000000004a817c800000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000027100000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000a5e0829caced8ffdd4de3c43696c57f7d7a678ff00000000000000000000000000000000000000000000000000000000000000020000000000000000000000008f3cf7ad23cd3cadbd9735aff958023239c6a0630000000000000000000000000d500b1d8e8ef31e21c99d1db9a6444d3adf12700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000040000000000000000000000000e592427a0aece92de3edee1f18e0157c0586156400000000000000000000000000000000000000000000000000000000000001f400000000000000000000000000000000000000000000000000000000000000020000000000000000000000000d500b1d8e8ef31e21c99d1db9a6444d3adf12700000000000000000000000008f3cf7ad23cd3cadbd9735aff958023239c6a063',
    accessList: [],
    hash: '0x8b6b1158e1ecb6c13a301c7b3cff8125e6cfc21843d34be5ca064f2df399ec2b',
    v: 1,
    r: '0xf27c77492b08862cf150d60f4236016c7708dc15b18047bc08187d275c3e9193',
    s: '0x5a0196fc0c30c1af25d798f10035205a89a7650b8354f60be649a7e140ef88dc',
    from: '0x936bb3D6492190FCf0d619a2f04DD54E622ad376',
    confirmations: 0
  },
  transactionHash: '0x8b6b1158e1ecb6c13a301c7b3cff8125e6cfc21843d34be5ca064f2df399ec2b'
}

**Comment by Solh4ckm1n** [comment]
I have the same problem has you, how many Matic do you have in your wallet ?

**Comment by pamarthisai** [comment]
yes i have 50 matic in my wallet

**Comment by Solh4ckm1n** [comment]
OMG got 50 failed transaction in the space of 5 minute

**Comment by pamarthisai** [comment]
no because that is all 0 confirmation transactions

**Comment by Solh4ckm1n** [comment]
[2022-06-03T14:09:40.232] [INFO] flashloan - path [ 'USDC', 'WMATIC', 'USDC' ] protocols [ 2 ]
[2022-06-03T14:09:40.232] [INFO] flashloan - {
  amount: '1705327203002940.5000',
  difference: 1705327203001940.5,
  percentage: 170532720300194.03
}
[2022-06-03T14:09:40.232] [INFO] flashloan - Explorer URL: https://polygonscan.com/tx/0x0e8317848926d867797ed68d8d7470860348941560877123cfaa685fb80f6eae
[2022-06-03T14:09:52.065] [INFO] flashloan - path [ 'USDC', 'WETH', 'USDC' ] protocols [ 2 ]
[2022-06-03T14:09:52.065] [INFO] flashloan - {
  amount: '564666449774.5935',
  difference: 564666448774.5935,
  percentage: 56466644877.46
}
[2022-06-03T14:09:52.066] [INFO] flashloan - Explorer URL: https://polygonscan.com/tx/0xdd3468409567077f4ccccfb15103acf1ed32464e2524a231490245778db185a4
[2022-06-03T14:09:59.643] [INFO] flashloan - path [ 'USDC', 'WETH', 'USDC' ] protocols [ 2 ]
[2022-06-03T14:09:59.643] [INFO] flashloan - {
  amount: '564666449774.5935',
  difference: 564666448774.5935,
  percentage: 56466644877.46
}
[2022-06-03T14:09:59.643] [INFO] flashloan - Explorer URL: https://polygonscan.com/tx/0xdc2261172695f9620a29c93c38fc3c11ccf8ff917abbd0288180cfe899c755fa
[2022-06-03T14:10:11.660] [INFO] flashloan - path [ 'USDC', 'WETH', 'USDC' ] protocols [ 2 ]
[2022-06-03T14:10:11.660] [INFO] flashloan - {
  amount: '564666167824.6996',
  difference: 564666166824.6996,
  percentage: 56466616682.47
}
[2022-06-03T14:10:11.660] [INFO] flashloan - Explorer URL: https://polygonscan.com/tx/0x278c832ca6cde422c446fef99bbd3af82eb390131a8afdcffafe6ea8df598bbc
[2022-06-03T14:10:15.908] [INFO] flashloan - path [ 'USDC', 'WETH', 'USDC' ] protocols [ 2 ]
[2022-06-03T14:10:15.908] [INFO] flashloan - {
  amount: '564666167824.6996',
  difference: 564666166824.6996,
  percentage: 56466616682.47
}
[2022-06-03T14:10:15.908] [INFO] flashloan - Explorer URL: https://polygonscan.com/tx/0x1eda0bc0d02c640fbc22104c7133f7d383825b51c55fc5c14db63631c7fa0480
[2022-06-03T14:10:19.555] [INFO] flashloan - path [ 'USDC', 'WETH', 'USDC' ] protocols [ 2 ]
[2022-06-03T14:10:19.555] [INFO] flashloan - {
  amount: '564666167824.6996',
  difference: 564666166824.6996,
  percentage: 56466616682.47
}
[2022-06-03T14:10:19.555] [INFO] flashloan - Explorer URL: https://polygonscan.com/tx/0xea790d10bc579fcf662c2423648a00ac6c3d7fe768fe50358ba624f1a62d13aa

**Comment by pamarthisai** [comment]
percentage 56466616682.47 confused

**Comment by pamarthisai** [comment]
or u can ping me telegram:  pamarthisai

**Comment by Arond-Devv** [comment]
Have you able to resolved your issues?
